spring:
#  liquibase:
#    change-log: db/changelog/db.master-changelog.yaml

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/resources/db/game.db
    password:
    username:

  jpa:
    show: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect

logging:
  file: my.log
